AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - 'rails_simple_event_sourcing.gemspec'
    - 'vendor/bundle/**/*'

Layout/LineLength:
  Max: 120
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false
